version = "1.0.0"

[Details]
  name = "Kochurov Roman"
  birthday = 1994-09-16T08:00:00+06:00 
  postion = "Software Engineer"
  location = "Tomsk, Russia"
  citizenship = "Kazakhstan" 
  timezone = "UTC+7"
  phone = "+79234221994"
  github = "https://github.com/kochurovro"

[Summary]
  text = """
  Software engineer who is open to new opportunities and is ready for a next step in my career path. 
  After two years of working on LinkIT services I have confidence the platform can easily expand without my efforts.
  I'm looking for a company that will help my engineering skills further grow and will provide me with adequate challenges.
  Primarily interested in a remote position but I'm open to all offers.
  """

[Experience]
  
  [Experience.LinkIT360]
    year_start = 2018-01-01T00:00:00+07:00
    year_end = "present"
    location = "Remote"
    postion = "Go developer"
    url = "http://www.linkit360.com/"
    description = "Mobile Payments for business"
    summary = """
    Work experience in the small team. Tasks in the team are diverse.
    Role was growing from implementation an non-scalable architecture for new providers to a scalable architecture design.
    Each new provider was the responsibility of one developer where you need to implement all service stages from development to deployment.
    """
    technology_stack = ["Go", "PostgreSQL", "Docker", "Docker-Compose", "Nginx", "Gitlab CI/CD", "Swagger", "RabbitMQ", "Linux"]

  [Experience.CenteraSoft]
    year_start = 2017-09-01T00:00:00+07:00
    year_end = 2017-12-01T00:00:00+07:00
    location = "Tomsk"
    postion = "Junior C# developer"
    summary = "The main task was developing a service of migrating Events"
    technology_stack = [".NET Core", "Azure Storage", "TDD", "Git"]

[Education]
  year_end = 2016
  degree = "Applied mathematics and computer science (Bachelor)"
  university = "National Research Tomsk State University"
  department = "Institute of Applied Mathematics and Computer Science"
  url = "http://www.tsu.ru/"
